### ISSUE TITLE
Add Build Info

### ISSUE THREAD

**Issue by wkulhanek** [e-minguez/file-to-machineconfig#4]
Super neat!!
Would it be possible to add
a) build information
b) releases (pre-built binaries)

**Comment by e-minguez** [comment]
I've just 'released' a first 0.0.1 version and I will update the README just in case.
Thanks for the feedback!

**Comment by e-minguez** [comment]
@wkulhanek I've added some notes in the README wrt releases/how to build. Let me know if it works or if it can be improved.

Thanks!

**Comment by wkulhanek** [comment]
@e-minguez Thank you!! Release is awesome - I would suggest adding the architecture to the filename (I assume this is Linux...amd64)

I just tried the go get. Works great. It needs a second step though: cd into the directory ($GOPATH/src/github.com/e-minguez/file-to-machineconfig and then "go build".

**Comment by e-minguez** [comment]
> @e-minguez Thank you!! Release is awesome - I would suggest adding the architecture to the filename (I assume this is Linux...amd64)
> 

Done, I've added the Linux one and an untested OSX build just in case :)

> I just tried the go get. Works great. It needs a second step though: cd into the directory ($GOPATH/src/github.com/e-minguez/file-to-machineconfig and then "go build".

If you have your proper GOPATH and PATH, go get should create the binary automatically:

```
$ sudo dnf install -y golang
$ mkdir go
$ export GOPATH=~/go
$ export PATH=~/go/bin:$PATH
$ go get -u -v github.com/e-minguez/file-to-machineconfig
$ file-to-machineconfig
```

**Comment by e-minguez** [comment]
I think the README has enough information now so I'm closing this.
Thanks for reporting it @wkulhanek !
